services:
  mysql:
    container_name: DB
    image: mysql:8.3
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: market
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./SQL QUERIES/user.sql:/docker-entrypoint-initdb.d/user.sql
    
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: DB
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    depends_on:
      - mysql